# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"E\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x11\n\tserver_id\x18\x03 \x01(\x05\"q\n\x0c\x43hatResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t\x12\x1c\n\x14is_approval_required\x18\x02 \x01(\x08\x12,\n\x13proposed_tool_calls\x18\x03 \x03(\x0b\x32\x0f.agent.ToolCall\"E\n\x08ToolCall\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t2?\n\x0c\x41gentService\x12/\n\x04\x43hat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=22
  _globals['_CHATREQUEST']._serialized_end=91
  _globals['_CHATRESPONSE']._serialized_start=93
  _globals['_CHATRESPONSE']._serialized_end=206
  _globals['_TOOLCALL']._serialized_start=208
  _globals['_TOOLCALL']._serialized_end=277
  _globals['_AGENTSERVICE']._serialized_start=279
  _globals['_AGENTSERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
